### ISSUE TITLE
Unable to run the auth command

### ISSUE THREAD

**Issue by asivaneswaran** [franznkemaka/fluidbm-cli#4]
Everytime I run the fluidbm command,  I get this error:
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "fluidbm-cli@1.0.0" with binaries:
      - fluidbm
✨  Done in 2.47s.
❯ fluidbm auth
env: node\r: No such file or directory

**Comment by IfnotFr** [comment]
Same here, using ubuntu :(

**Comment by franznkemaka** [comment]
Hi @IfnotFr, @asivaneswaran,

this library was for a while on hold, I'll investigate and update you guys.

**Comment by franznkemaka** [comment]
@IfnotFr @asivaneswaran did you encounter the issue recently?

Possible fix: https://github.com/franznkemaka/fluidbm-cli/issues/2#issuecomment-1370434191

**Comment by franznkemaka** [comment]
I have great news, Fludibm v1.0 is back online! 🚀🚀🚀🚀

We are looking forward to suggestions and ideas!
Next step will be Fluidbm 2.0
