### ISSUE TITLE
i m try to use but ... dont work :(

### ISSUE THREAD

**Issue by nextstage-brasil** [franznkemaka/fluidbm-cli#5]
root@52df5b275184:/var/www/html# npx fluidbm clone 640c7d17e04d5b9c2b8320c1
  _____   _           _       _   _                 
 |  ___| | |  _   _  (_)   __| | | |__    _ __ ___  
 | |_    | | | | | | | |  / _` | | '_ \  | '_ ` _ \ 
 |  _|   | | | |_| | | | | (_| | | |_) | | | | | | |
 |_|     |_|  \__,_| |_|  \__,_| |_.__/  |_| |_| |_|
                                                    
Unable to extract schema ID from input: undefined
root@52df5b275184:/var/www/html#

**Comment by franznkemaka** [comment]
Hi @nextstage-brasil, 

Did you sign in using fluidbm auth with your token before?

**Comment by franznkemaka** [comment]
Hi @dreanmer thanks for letting me know!

I have great news, Fludibm v1.0 is back online! 🚀🚀🚀🚀

We are looking forward to suggestions and ideas!
Next step will be Fluidbm 2.0
