### ISSUE TITLE
fluidbm.com is down - http 503

### ISSUE THREAD

**Issue by dreanmer** [franznkemaka/fluidbm-cli#8]
I'm trying to access https://fluidbm.com/ but got 503. Are the servers down? Can I help with anything?

**Comment by tikumo** [comment]
Still down :(

**Comment by franznkemaka** [comment]
Hi guys, thanks for letting me know I'll put it back up

**Comment by franznkemaka** [comment]
Hi @dreanmer thanks for letting me know!

I have great news, Fludibm v1.0 is back online! 🚀🚀🚀🚀

We are looking forward to suggestions and ideas!
Next step will be Fluidbm 2.0

**Comment by franznkemaka** [comment]
> Still down :(

Hi @tikumo  thanks for letting me know!

I have great news, Fludibm v1.0 is back online! 🚀🚀🚀🚀

We are looking forward to suggestions and ideas!
Next step will be Fluidbm 2.0
